//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midias.BTSCs.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public int Id { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
